name: Tests
on: push
jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --workspace --all-targets
  
